# Generated by Django 3.1.7 on 2021-04-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('comment', models.TextField()),
                ('rating', models.CharField(max_length=1)),
            ],
        ),
    ]
