# Generated by Django 3.2 on 2021-04-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_tab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='time_duration',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_duration',
            field=models.CharField(default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_for_res',
            field=models.CharField(max_length=6),
        ),
    ]
