# Generated by Django 3.2 on 2021-04-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_tab', '0002_auto_20210417_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_duration',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_for_res',
            field=models.TimeField(),
        ),
    ]
