# Generated by Django 3.2 on 2021-04-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_tab', '0003_auto_20210417_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dining_table',
            name='phone_occupied',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
