# Generated by Django 3.2 on 2021-04-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(null=True)),
                ('item_name', models.CharField(max_length=200, null=True)),
                ('selling_price', models.IntegerField(null=True)),
            ],
        ),
    ]
