# Generated by Django 3.2 on 2021-04-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='order_frequency',
            field=models.IntegerField(default=0),
        ),
    ]
