# Generated by Django 3.2 on 2021-04-17 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0002_auto_20210417_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_quantity', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takeaway.inventory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takeaway.menu_item')),
            ],
        ),
    ]
