# Generated by Django 3.2 on 2021-04-29 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0002_menu_item_order_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('amount', models.IntegerField(help_text='in grams')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takeaway.inventory')),
            ],
        ),
    ]
