# Generated by Django 3.2 on 2021-04-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0003_ingredient_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient_list',
            name='use_quantity',
            field=models.IntegerField(help_text='in grams'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='cost_price',
            field=models.IntegerField(help_text='cost per gram'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='min_quantity',
            field=models.IntegerField(help_text='in grams'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(help_text='in grams'),
        ),
    ]
