# Generated by Django 3.2 on 2021-04-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loyalty_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_points', models.IntegerField()),
                ('discount_perc', models.IntegerField()),
            ],
        ),
    ]
