# Generated by Django 3.2 on 2021-04-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='earned',
            field=models.IntegerField(default=0, help_text='Money earned from sale'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='spent',
            field=models.IntegerField(default=0, help_text='Money spent on ingredients'),
        ),
    ]
