# Generated by Django 3.2 on 2021-04-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0002_loyalty_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('spent', models.IntegerField(help_text='Money spent on ingredients')),
                ('earned', models.IntegerField(help_text='Money earned from sale')),
            ],
        ),
    ]
