# Generated by Django 3.2 on 2021-04-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0003_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='area_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
