# Generated by Django 3.2 on 2021-04-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0004_auto_20210416_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area_code',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
