# Generated by Django 3.2 on 2021-04-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0006_alter_user_area_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_code', models.IntegerField(blank=True, default=None, null=True)),
                ('available_stat', models.IntegerField(choices=[(0, 0), (1, 1)])),
                ('phone', models.BigIntegerField()),
            ],
        ),
    ]
