# Generated by Django 3.2 on 2021-04-18 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=100, unique=True)),
                ('quantity', models.IntegerField(help_text='in grams')),
                ('min_quantity', models.IntegerField(help_text='in grams')),
                ('cost_price', models.IntegerField(help_text='cost per gram')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(null=True)),
                ('item_name', models.CharField(max_length=200, null=True, unique=True)),
                ('selling_price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_quantity', models.IntegerField(help_text='in grams')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takeaway.inventory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takeaway.menu_item')),
            ],
        ),
    ]
