# Generated by Django 3.2 on 2021-04-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_item',
            name='item_id',
        ),
    ]
