# Generated by Django 3.2 on 2021-04-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('area_code', models.IntegerField()),
                ('mon_spent', models.IntegerField()),
                ('loyalty', models.IntegerField()),
            ],
        ),
    ]
