# Generated by Django 3.2 on 2021-04-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0002_auto_20210415_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(default=None, null=True),
        ),
    ]
