# Generated by Django 3.2 on 2021-04-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_tab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dining_table',
            name='table_id',
            field=models.IntegerField(unique=True),
        ),
    ]
