# Generated by Django 3.2 on 2021-04-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_code', models.IntegerField(blank=True, default=None, null=True)),
                ('available_stat', models.IntegerField(choices=[(0, 0), (1, 1)])),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, default=None)),
                ('area_code', models.IntegerField(blank=True, default=None, null=True)),
                ('mon_spent', models.IntegerField()),
                ('loyalty', models.IntegerField()),
            ],
        ),
    ]
